<?php

namespace Tangara\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseStepRepository extends EntityRepository
{
    public function getCourseSteps(Course $course, Step $step) {
        $query = $this->createQueryBuilder('cs')
                ->where('cs.course = :course')
                ->andwhere('cs.step = :step')
                ->setParameter('course', $course)
                ->setParameter('step', $step);
        return $query->getQuery()->getResult();
    } 
    
}
