<?php

namespace Tangara\CoreBundle\Entity;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCourses(){
        return $this->findAll();
    }
    
}
