<?php

namespace Tangara\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{
    public function getProjectLogEntries($project){
        $query = $this->createQueryBuilder('p')
                ->where('p.project = :project')
                ->orderBy('p.timestamp', 'DESC')
                ->setParameter('project', $project);
        return $query->getQuery()->getResult();;
    }
    
}
