<?php

namespace Tangara\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Tangara\CoreBundle\Entity\User;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function getPublishedProjectsQuery(){
        $query = $this->createQueryBuilder('p')
                ->where('p.published = true')
                ->orderBy('p.created', 'DESC');
        
        return $query->getQuery();
    }
    
    public function getOwnedProjects(User $user) {
        $query = $this->createQueryBuilder('p')
                ->where('p.owner = :owner')
                ->orderBy('p.created', 'DESC')
                ->setParameter('owner', $user);
        
        $projects = $query->getQuery()->getResult();
        
        return $projects;
    }
    
    public function getReadonlyProjects(User $user){
        $query = $this->createQueryBuilder('p')
                ->where('p.readonly = true')
                ->andwhere('p.owner != :owner')
                ->orderBy('p.created', 'DESC')
                ->setParameter('owner', $user);
        
        $projects = $query->getQuery()->getResult();
        
        return $projects;
    }
    
    public function getSearchQuery($string, $published = false) {
        if (!$published) {
            $qb = $this->createQueryBuilder('p')
                        ->where('p.name like :name')
                        ->orderBy('p.id')
                        ->setParameter('name','%'.$string.'%');
            return $qb->getQuery();
        } else {
            $qb = $this->createQueryBuilder('p')
                        ->where('p.name like :name')
                        ->andWhere('p.published = true')
                        ->orderBy('p.created', 'DESC')
                        ->setParameter('name','%'.$string.'%');
            return $qb->getQuery();
        }
    }
    
    public function findAll($published = false) {
        if (!$published) {
            return parent::findAll();
        } else {
            return $this->getPublishedProjectsQuery();
        }
    }
    
}
