<?php

namespace Tangara\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository {

    public function getLastPosted($limit = 5) {
        return $this->getEntityManager()->createQuery('
        SELECT
            d
        FROM
            WmdWatchMyDeskBundle:Desk d
        WHERE
            d.isEnabled = :enabled
        ORDER BY
            d.updatedAt DESC,
            d.id DESC
        ')
                        ->setMaxResults($limit)
                        ->setParameter('enabled', true);
    }

}
