<?php

namespace Tangara\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository {

    public function getLastPostedSQL($limit = 5) {
        return $this->get('doctrine')->getManager()->createQuery('
            SELECT 
                email 
            FROM 
                `fos_user` 
            WHERE 
                `id` = 1 
    ');
    }

    //public function getProjects($group_id) {
    public function myFindAll() {
                return $this->get('doctrine')->getManager()->createQuery('
            SELECT 
                email 
            FROM 
                `fos_user` 
            WHERE 
                `id` = 1 
    ');
    }

    public function getForeignGroup($user_id) {
        
    }

    public function getLastPosted($limit = 5) {
        return $this->createQueryBuilder('d')
                        ->where('d.isEnabled = :enabled')
                        ->setParameter('enabled', true)
                        ->addOrderBy('d.updatedAt', "DESC")
                        ->addOrderBy('d.id', "DESC")
                        ->setMaxResults($limit);

    }

}
