#routing for AdminController
tangara_admin_index:
    path:  /index
    defaults: { _controller: TangaraCoreBundle:Admin:index }
    
tangara_admin_users:
    path:  /users
    defaults: { _controller: TangaraCoreBundle:Admin:users}

tangara_admin_users_list:
    path:  /get_users
    defaults: { _controller: TangaraCoreBundle:Admin:getUsers}
    
tangara_admin_projects:
    path:  /projects
    defaults: { _controller: TangaraCoreBundle:Admin:projects }

tangara_admin_projects_list:
    path:  /get_projects
    defaults: { _controller: TangaraCoreBundle:Admin:getProjects}

tangara_admin_exercises:
    path:  /exercises
    defaults: { _controller: TangaraCoreBundle:Admin:exercises }
    
tangara_admin_exercises_list:
    path:  /get_exercises
    defaults: { _controller: TangaraCoreBundle:Admin:getExercises}