tangara_core_homepage:
    path:  /
    defaults: { _controller: TangaraCoreBundle:Main:index }

tangara_core_info:
    path:  /info
    defaults: { _controller: TangaraCoreBundle:Main:info}
    
tangara_core_create:
    path:  /create
    defaults: { _controller: TangaraCoreBundle:Main:create}
